#!/usr/bin/env bash

. $RERUN_MODULE_DIR/lib/functions.sh test || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

trap 'rerun_die $? "*** command failed: deis:test. ***"' ERR

set -o nounset -o pipefail

source-defaults

load-env

rerun_options_parse "$@"

source-config

setup-ssh-agent

setup-test-hacks

{
  cd ${DEIS_ROOT}

  case "${TYPE}" in
    smoke)
      make test-smoke
      ;;
    full)
      make test-full
      ;;
  esac
}
