name: provision
source: github.com/deis/rig-flow-provision
description: |
  This workflow rig provides an easy way to spin up and test a set of cloud
  based infrastructure using that provider's cli or another tool such as
  Terraform

- name: up
  description: |
    run the underlying provisioning provider (AWS, GCE, DigitalOcean, etc.) in
    order to get a working pile of infrastructure to use for other things
  outputs:
    vars:
      - DEIS_HOST

- name: down
  description: |
    destroy all the created infrastructure provisioned in the "up" step
  inputs:
    vars:
      - DEIS_HOST

- name: check
  description: |
    run a quick healthcheck of the infrastructure that was supposedly created
    during the "up" step
  inputs:
    vars:
      - DEIS_HOST

- name: test
  description: |
    run a longer test of the infrastructure in order to _really_ verify that
    the infrastructure is available
  inputs:
    vars:
      - DEIS_HOST
