#!/usr/bin/env bash

. $RERUN_MODULE_DIR/lib/functions.sh shellinit || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

trap 'rerun_die $? "*** command failed: deis:shellinit. ***"' ERR

set -o nounset -o pipefail

rerun_options_parse "$@"

source-defaults

cat ${FILE:-${DEIS_TEST_ENV}}
