RERUN_DEIS_ROOT="${HOME}/.rigger"

UPGRADER_DIR="${RERUN_MODULE_DIR}/options/upgrade-style"

DEIS_TEST_ENV="${RERUN_DEIS_ROOT}/vars"

TERRAFORM_DIR="${RERUN_DEIS_ROOT}/terraform"


DEIS_TEST_ID=${DEIS_TEST_ID:-$(openssl rand -hex 5)}
DEIS_TEST_ROOT="${RERUN_DEIS_ROOT}/${DEIS_TEST_ID}"
DEIS_VARS_FILE="${DEIS_TEST_ROOT}/vars"

SUGGEST_DEV_REGISTRY="registry.hub.docker.com"
SUGGEST_GOPATH="${HOME}/go"

DEIS_BIN_DIR="${DEIS_TEST_ROOT}/bin"
DEISCLI_BIN="${DEIS_BIN_DIR}/deis"
DEISCTL_BIN="${DEIS_BIN_DIR}/deisctl"
DEISCTL_UNITS="${DEIS_TEST_ROOT}/units"