#!/usr/bin/env bash

. $RERUN_MODULE_DIR/lib/functions.sh provision || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

trap 'rerun_die $? "*** command failed: tests:provision. ***"' ERR

set -o nounset -o pipefail

source-defaults

load-env

rerun_options_parse "$@"

source-config

trap destroy-cluster EXIT

setup-provider "${PROVIDER}"

setup-provider-dependencies

destroy-cluster

setup-clients "${DEIS_VERSION}"

{
  cd ${DEIS_ROOT}
  make discovery-url
}

setup-ssh-agent

create-cluster

deploy-deis "${DEIS_VERSION}"
