#!/usr/bin/env bash

. $RERUN_MODULE_DIR/lib/functions.sh upgrade || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

trap 'rerun_die $? "*** command failed: tests:upgrade. ***"' ERR

set -o nounset -o pipefail

source-defaults

load-env

rerun_options_parse "$@"

source-config

trap destroy-cluster EXIT

function healthcheck {
  rerun_log "Running healthcheck of previously deployed app.."

  if ! curl -s "http://testing.${DEIS_TEST_DOMAIN}" | grep -q "Powered by Deis"; then
    rerun_log error "Failed to pass healthcheck."
    return 1
  else
    rerun_log info "Healthcheck succeeded."
    return 0
  fi
}

setup-upgrader "${UPGRADE_STYLE}"

save-var UPGRADE_STYLE

setup-ssh-agent

upgrade-deis "${DEIS_VERSION}" "${TO}"

healthcheck
